name: Test and build

on:
  push

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Start rocket.chat server
        uses: isbang/compose-action@v0.1.1
        with:
          compose-file: docker-compose-test-server.yml
